### ISSUE TITLE
UtilityScripts dir is not found. 

### ISSUE THREAD

**Issue by vherrin** [IBM-Swift/Kitura-HelloWorld-iOS#1]
The prereqs specify UtilityScripts path but what I’m seeing is Builder/Scripts instead.  Also in the buildCurlStaticLibrary.sh file there is the same dir path of UtilityScripts.  Is there a step that I'm missing?

**Comment by vadimeisenbergibm** [comment]
Fixed in commits:
https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/commit/7f6dd15b2f719e623c7391f15526e837d64ee017
https://github.com/IBM-Swift/Kitura-HelloWorld-iOS/commit/166fa1cf74f4984cc093f89e01eecf6925920b90

Instead of `UtilityScripts`, `Builder/Scripts` should be used, after running `make Builder/Makefile`
